require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  DisplayCopNames: true
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'script/**/*'
    - 'spec/**/*'
    - 'vendor/**/*'
    - 'frontend/**/*'

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Exclude: []

Metrics/PerceivedComplexity:
  Exclude: []

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Exclude: []
  CountComments: false  # count full line comments?
  Max: 250

Metrics/ModuleLength:
  Exclude: []

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Layout/BlockEndNewline:
  Exclude:
    - 'spec/**/*'

Layout/MultilineBlockLayout:
  Exclude:
    - 'spec/**/*'

Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

Style/WordArray:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  Exclude: []

Style/LineEndConcatenation:
  Exclude: []

Naming/PredicateName:
  Exclude: []

Style/GlobalVars:
  Exclude:
    - 'spec/**/*'

Style/SingleLineBlockParams:
  Enabled: false

Style/ClassVars:
  Exclude: []

Style/SignalException:
  Enabled: false

Rails:
  Enabled: true

Rails/ActionFilter:
  EnforcedStyle: action
  Include:
    - app/controllers/**/*.rb

Rails/Output:
  Exclude:
    - 'lib/generators/**/*'
    - 'lib/uri_service/utils/logger.rb'
    - 'config/deploy.rb'

Rails/Date:
  Enabled: false

Rails/TimeZone:
  Enabled: false

RSpec/ExampleWording:
  CustomTransform:
    be: is
    have: has
    not: does not
    NOT: does NOT
  IgnoredWords:
    - only

RSpec/FilePath:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/features/**/*'
    - 'spec/views/**/*'
    - 'spec/routing/**/*'
