language: ruby
cache: bundler
sudo: false

rvm:
  - 2.3.0
jdk: 'oraclejdk8'

matrix:
  include:
   - rvm: 2.4.1
   - rvm: 2.2.4

notifications:
  irc: "irc.freenode.org#ldpddev"

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

script: bundle exec rake cul_hydra_models:ci